[terminal]
shell = { program = "pwsh", args = ["-NoExit", "-Command", "C:\\dev\\psprofile.ps1"] }

[general]
working_directory = "C:\\dev"
live_config_reload = true

[window]
dimensions = { columns = 140, lines = 40 }
decorations = "Full"
decorations_theme_variant = "Light" # "Dark"
opacity = 0.92

startup_mode = "Windowed"

title = "Alacritty"
dynamic_title = false

[font]
builtin_box_drawing = true

# Campbell (Windows 10 default)
# Default colors
[colors.primary]
background = '#0c0c0c'
foreground = '#cccccc'

# Normal colors
[colors.normal]
black      = '#0c0c0c'
red        = '#c50f1f'
green      = '#13a10e'
yellow     = '#c19c00'
blue       = '#0037da'
magenta    = '#881798'
cyan       = '#3a96dd'
white      = '#cccccc'

# Bright colors
[colors.bright]
black      = '#767676'
red        = '#e74856'
green      = '#16c60c'
yellow     = '#f9f1a5'
blue       = '#3b78ff'
magenta    = '#b4009e'
cyan       = '#61d6d6'
white      = '#f2f2f2'
